### ISSUE TITLE
Implement a plugin for traefik that checks incoming shlink urls for valid app shortcut links

### ISSUE THREAD

**Issue by PhilippMatthes** [priobike/shlink-guard#1]
Currently, our shlink service accepts any kind of long url, which could be abused. The goal of this plugin is to check whether requested urls for a shlink are a valid shortcut from the PrioBike app.

**Comment by adeveloper-wq** [comment]
Fix TODO: https://github.com/priobike/priobike-shlink-guard/blob/5ddd0b6de2be2d8737deffee64944f7a3c84e026/main.go#L56

Add check to `GET` requests: https://github.com/priobike/priobike-shlink-guard/blob/5ddd0b6de2be2d8737deffee64944f7a3c84e026/main.go#L27-L31
- We want to allow: [/rest/v{version}/short-urls/{shortCode}](https://api-spec.shlink.io/#/Short%20URLs/getShortUrl)
- We want to block: [/rest/v{version}/short-urls](https://api-spec.shlink.io/#/Short%20URLs/listShortUrls)

**Comment by adeveloper-wq** [comment]
Deployed in staging now, doesn't work however. Going to look into it tomorrow.

**Comment by adeveloper-wq** [comment]
Works now. Was a cache problem.
